### PR TITLE
fix email_activate views & Email2FA identity code -> secret

### PR DESCRIPTION
**Pull request by jozefrebjak**

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
I'm not familiar with those HTML tag properties but you seem to know what you are doing.

**Comment by jozefrebjak** [comment]
@MGatner HTML tags are the same as in the Email 2FA verify view [email_2fa_verify](https://github.com/lonnieezell/codeigniter-shield/blob/develop/src/Views/email_2fa_verify.php)

**Comment by MGatner** [comment]
Ah gotcha! Thanks for pointing that out. Doubly-approved! 👍👍

**Comment by kenjis** [comment]
A test failed. I will fix it.

```
There was 1 failure:

1) Tests\Controllers\ActionsTest::testEmailActivateShow
Failed asserting that '<!-- DEBUG-VIEW START 1 /home/runner/work/codeigniter-shield/codeigniter-shield/src/Views/email_activate_email.php -->\n
<p>Please click the link below to activate your account and start using the site.</p>\n
\n
<p><a href="https://example.com/index.php/auth/a/verify?token=345287">https://example.com/index.php/auth/a/verify</a></p>\n
\n
<!-- DEBUG-VIEW ENDED 1 /home/runner/work/codeigniter-shield/codeigniter-shield/src/Views/email_activate_email.php -->' contains "/auth/a/verify?c=".

/home/runner/work/codeigniter-shield/codeigniter-shield/tests/Controllers/ActionsTest.php:221
```
https://github.com/lonnieezell/codeigniter-shield/runs/6075197185?check_suite_focus=true

**Pull request merged**
