### PR TITLE
Update Toolkit

### PR DESCRIPTION
**Pull request by MGatner**
* Fixes some issues with the integration workflows
* Updates PHPStan to `^1.0` and applies analysis fixes

### CODE REVIEW

**Comment by MGatner** [comment]
The PHPUnit failures are unrelated to this change and must be due to some upstream changes (CodeIgniter framework probably?). @lonnieezell I'm not sure how you want to handle that but it's beyond the scope of what I'm doing in this PR.

**Review by lonnieezell — APPROVED** [review]
I'm fine with this one. Feel free to merge after the conflict is resolved.

**Comment by MGatner** [comment]
@lonnieezell I don't have write access here :) But rebase is complete.

**Comment by lonnieezell** [comment]
>  I don't have write access here :) But rebase is complete.

Doh! Very true. :) Merging.

**Pull request merged**
