### PR TITLE
docs: use "remember-me" everywhere

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Comment by lonnieezell** [comment]
I'm not sure I see it hyphenated like that very often. What prompted this change?

**Comment by kenjis** [comment]
Since *remember-me* seemed to be the most commonly used in the source code comments, I adapted it.
It is easy to search.

**Comment by MGatner** [comment]
I like the hyphen or quotes:
* remember-me token
* "remember me" token

We could also use a noun adjunct:
* remembrance token
* persistence token

**Comment by lonnieezell** [comment]
I guess I didn't remember I had hyphenated it anywhere lol

We can hyphenate, that's fine.

**Pull request merged**
