### PR TITLE
chore: add Psalm

### PR DESCRIPTION
**Pull request by kenjis**
See https://psalm.dev/

The current type coverage is 81%.

> Psalm was able to infer types for 81.4696% of the codebase

### CODE REVIEW

**Comment by lonnieezell** [comment]
Why do we need a second static analysis tool?

**Comment by kenjis** [comment]
Psalm could fix types in some places automatically.

**Review by MGatner — COMMENTED** [review]
What does Psalm bring that isn't covered by PHPStan and Rector? If there is a significant contribution, should we incorporate this into the DevKit as well?

**Comment by MGatner** [comment]
Ah sorry I missed the conversation above. CS Fixer can convert docblock types to actual types (`phpdoc_to_property_types => true`). Rector also has a rule to do the same. Is Psalm somehow deriving typed from their context, at a deeper level than these two?

**Comment by kenjis** [comment]
@MGatner I think we should use Psalm, too.

Checkout this PR, and try.

```
$ gh pr checkout #52
$ composer update
$ vendor/bin/psalm
$ vendor/bin/psalm --show-info=true
```

**Review by lonnieezell — APPROVED** [review]

**Pull request merged**
